### PR TITLE
Support to add the `SuppressIldasm` as assembly.

### PR DESCRIPTION
**Pull request by alexchicn**
I found this situation: If the obfuscated dll still can run in the Unity3D, you should make the `SuppressIldasm` as assembly.
So I make a tiny revision to support this function.

### CODE REVIEW

**Comment by lextm** [comment]
How does the configuration file look like after this change? Meanwhile can you show the related Unity documentation?

**Comment by alexchicn** [comment]
Old version:
`<Module file="$(InPath)\BasicExampleLibrary.dll" />`
New version:
`<Assembly file="$(InPath)\BasicExampleLibrary.dll" />`
Both formats are supported in the commit.

The most importance code (in the file - `Obfuscar/Obfuscator.cs`):
1. `module.CustomAttributes.Add(attr);`
2. `module.Assembly.CustomAttributes.Add (attr);`

I can't find any information about the dll assembly in the Unity3D documentation. But I found that it is doesn't work when the `SuppressIldasm` was added as `module` in the Unity3D. So I need to add the `SuppressIldasm` as `assembly`.

**Comment by lextm** [comment]
It would be strange to have `<Assembly />` added to the configuration, solely for this feature. `<Module />` has already served us well. I'd like to accept your changes in `Obfuscator.cs` though.

Can you update your PR? Besides, you might need to rebase it against the current master.

Thanks.

**Comment by alexchicn** [comment]
My PR? 
Public Relation? I am just a code lover, and live in Shanghai. You can find more information from [here](https://github.com/alexchicn).

**Comment by lextm** [comment]
@alexchicn I mean this pull request.

**Comment by alexchicn** [comment]
Okay, I solved the conflict.

**Pull request merged**
